# Generated by Django 5.2.4 on 2025-07-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cphoto', models.URLField(max_length=5000)),
                ('cphone', models.CharField(max_length=10)),
                ('caddress', models.CharField(max_length=200)),
            ],
        ),
    ]
