# Generated by Django 5.2.4 on 2025-07-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cphoto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
