# Generated by Django 5.2.4 on 2025-08-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoree', '0004_alter_customer_cphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cphoto',
            field=models.ImageField(upload_to='images'),
        ),
    ]
