# Generated by Django 5.2.4 on 2025-08-04 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoree', '0005_alter_customer_cphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.DecimalField(decimal_places=2, max_digits=10)),
                ('febraury', models.DecimalField(decimal_places=2, max_digits=10)),
                ('march', models.DecimalField(decimal_places=2, max_digits=10)),
                ('april', models.DecimalField(decimal_places=2, max_digits=10)),
                ('may', models.DecimalField(decimal_places=2, max_digits=10)),
                ('june', models.DecimalField(decimal_places=2, max_digits=10)),
                ('july', models.DecimalField(decimal_places=2, max_digits=10)),
                ('august', models.DecimalField(decimal_places=2, max_digits=10)),
                ('september', models.DecimalField(decimal_places=2, max_digits=10)),
                ('october', models.DecimalField(decimal_places=2, max_digits=10)),
                ('november', models.DecimalField(decimal_places=2, max_digits=10)),
                ('december', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystoree.customer')),
            ],
        ),
    ]
