# Generated by Django 5.2.4 on 2025-08-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoree', '0006_monthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cphoto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
