# Generated by Django 5.2.4 on 2025-08-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoree', '0007_alter_customer_cphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cphoto',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
