# Generated by Django 5.2.4 on 2025-08-11 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoree', '0008_alter_customer_cphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mystoree.customer'),
        ),
    ]
