# Generated by Django 5.2.4 on 2025-11-20 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoree', '0009_alter_monthly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon', to='mystoree.customer'),
        ),
    ]
